words = {
        "abandon": "W3",
        "ability": "S2, W1",
        "able": "S1, W1",
        "about": "S1, W1",
        "above": "S2, W1",
        "abroad": "S2, W3",
        "absence": "S3, W2",
        "absolute": "S2, W3",
        "absolutely": "S1, W3",
        "absorb": "W3",
        "abuse": "S2, W3",
        "academic": "W2",
        "accept": "S1, W1",
        "acceptable": "S3, W3",
        "access": "S2, W1",
        "accident": "S2, W2",
        "accommodation": "S2, W2",
        "accompany": "W2",
        "according to": "S2, W1",
        "account": "S1, W1",
        "accurate": "S2, W3",
        "accuse": "W3",
        "achieve": "S2, W1",
        "achievement": "S3, W2",
        "acid": "W3",
        "acknowledge": "S3, W3",
        "acquire": "W2",
        "across": "S1, W1",
        "act": "S1, W1",
        "action": "S1, W1",
        "active": "S2, W2",
        "activist": "S3",
        "activity": "S2, W1",
        "actor": "W3",
        "actual": "S1, W2",
        "actually": "S1, W1",
        "ad": "S3, W3",
        "adapt": "W3",
        "add": "S1, W1",
        "addition": "S3, W1",
        "additional": "S3, W2",
        "address": "S2, W2",
        "adequate": "S3, W3",
        "adjust": "W3",
        "administration": "S2, W2",
        "administrative": "W3",
        "admire": "S3",
        "admission": "W3",
        "admit": "S2, W1",
        "adopt": "S3, W2",
        "adult": "S2, W2",
        "advance": "S2, W2",
        "advanced": "W3",
        "advantage": "S2, W1",
        "advert": "S3",
        "advertise": "S3, W3",
        "advertisement": "S3",
        "advertising": "W3",
        "advice": "S2, W2",
        "advise": "S2, W2",
        "adviser": "S3, W3",
        "affair": "S2, W1",
        "affect": "S2, W1",
        "afford": "S1, W3",
        "afraid": "S1, W2",
        "after": "S1, W1",
        "afternoon": "S1, W2",
        "afterwards": "S2, W3",
        "again": "S1, W1",
        "against": "S1, W1",
        "age": "S1, W1",
        "aged": "W3",
        "agency": "S3, W1",
        "agent": "S3, W2",
        "aggressive": "S3",
        "ago": "S1, W1",
        "agree": "S1, W1",
        "agreement": "S2, W1",
        "agriculture": "W2",
        "ahead": "S1, W2",
        "aid": "S2, W2",
        "aim": "S2, W2",
        "air": "S1, W1",
        "aircraft": "S2, W2",
        "airline": "S2, W3",
        "airport": "S3, W3",
        "alarm": "S2",
        "album": "S3, W3",
        "alcohol": "W3",
        "alive": "S2, W3",
        "all": "S1, W1",
        "allow": "S1, W1",
        "allowance": "S2, W3",
        "all right": "S1, W2",
        "almost": "S1, W1",
        "alone": "S2, W1",
        "along": "S1, W1",
        "alongside": "W3",
        "already": "S1, W1",
        "also": "S1, W1",
        "alter": "S3, W3",
        "alternative": "S2, W2",
        "although": "S1, W1",
        "altogether": "S2, W3",
        "always": "S1, W1",
        "amazing": "S2",
        "ambition": "W3",
        "ambulance": "S3",
        "among": "S2, W1",
        "amount": "S1, W1",
        "an": "S1, W1",
        "analyse": "W3",
        "analysis": "S3, W1",
        "analyst": "W2",
        "ancient": "W2",
        "and": "S1, W1",
        "anger": "W3",
        "angle": "S3, W3",
        "angry": "S3, W3",
        "animal": "S1, W1",
        "announce": "S2, W1",
        "announcement": "S3, W3",
        "annoy": "S3",
        "annual": "S2, W2",
        "another": "S1, W1",
        "answer": "S1, W1",
        "anticipate": "S3",
        "anxiety": "S3, W3",
        "anxious": "S3, W3",
        "any": "S1, W1",
        "anybody": "S1, W3",
        "anyhow": "S3",
        "anyone": "S1, W1",
        "anything": "S1, W1",
        "anyway": "S1, W2",
        "anywhere": "S1, W3",
        "apart": "S2, W1",
        "apartment": "S2, W3",
        "apologize": "S2",
        "apology": "S3",
        "apparent": "W2",
        "apparently": "S1, W2",
        "appeal": "S2, W1",
        "appear": "S2, W1",
        "appearance": "W2",
        "apple": "S2, W3",
        "application": "S1, W1",
        "apply": "S1, W1",
        "appoint": "S2, W2",
        "appointment": "S2, W2",
        "appreciate": "S2, W3",
        "approach": "S2, W1",
        "appropriate": "S2, W1",
        "approval": "S2, W3",
        "approve": "S3, W2",
        "approximate": "S3, W3",
        "architect": "W3",
        "architecture": "S3, W3",
        "area": "S1, W1",
        "argue": "S2, W1",
        "argument": "S1, W1",
        "arise": "S3, W2",
        "arm": "S1, W1",
        "armed": "S3, W3",
        "army": "S1, W1",
        "around": "S1, W1",
        "arrange": "S2, W2",
        "arrangement": "S2, W2",
        "arrest": "W3",
        "arrival": "W3",
        "arrive": "S2, W1",
        "art": "S1, W1",
        "article": "S2, W1",
        "artificial": "S3",
        "artist": "S3, W2",
        "as": "S1, W1",
        "ashamed": "S3",
        "aside": "S3, W3",
        "ask": "S1, W1",
        "asleep": "S2",
        "aspect": "S2, W1",
        "assess": "S2, W2",
        "assessment": "S3, W2",
        "assignment": "S2",
        "assist": "S3, W3",
        "assistance": "S3, W2",
        "assistant": "S3",
        "associate": "S3, W2",
        "association": "S3, W1",
        "assume": "S2, W1",
        "assumption": "S2, W2",
        "assure": "S2, W3",
        "at": "S1, W1",
        "atmosphere": "S3, W2",
        "attach": "S2, W2",
        "attack": "S2, W2",
        "attempt": "S2, W1",
        "attend": "S2, W2",
        "attention": "S2, W1",
        "attitude": "S2, W1",
        "attorney": "S2, W3",
        "attract": "S2, W2",
        "attraction": "W3",
        "attractive": "S2, W2",
        "audience": "S2, W2",
        "aunt": "S3, W3",
        "author": "W2",
        "authority": "W1",
        "automatic": "S3",
        "automatically": "S3, W3",
        "autumn": "W3",
        "available": "S1, W1",
        "average": "S2, W2",
        "avoid": "S2, W1",
        "awake": "S3",
        "award": "S3, W2",
        "aware": "S1, W1",
        "awareness": "W3",
        "away": "S1, W1",
        "awful": "S1",
        "awkward": "S3",
        "baby": "S1, W1",
        "back": "S1, W1",
        "background": "S2, W2",
        "backwards": "S3",
        "bacon": "S3",
        "bad": "S1, W1",
        "badly": "S3, W3",
        "bag": "S1, W2",
        "bake": "S3",
        "balance": "S2, W2",
        "ball": "S1, W2",
        "ban": "W3",
        "band": "S2, W2",
        "bang": "S3",
        "bank": "S1, W1",
        "bar": "S1, W1",
        "barrier": "W3",
        "base": "S1, W1",
        "baseball": "S3, W2",
        "basic": "S2, W1",
        "basically": "S1",
        "basis": "S2, W1",
        "basket": "S3",
        "bat": "S3",
        "bath": "S2, W3",
        "bathroom": "S2, W3",
        "battery": "S2",
        "battle": "W2",
        "be": "S1, W1",
        "beach": "S2, W2",
        "bean": "S2",
        "bear": "S2, W2",
        "beard": "S3",
        "beat": "S2, W2",
        "beautiful": "S1, W2",
        "beauty": "S3, W2",
        "because": "S1, W1",
        "become": "S1, W1",
        "bed": "S1, W1",
        "bedroom": "S1, W2",
        "beef": "S3",
        "beer": "S2, W3",
        "before": "S1, W1",
        "beforehand": "S3",
        "begin": "S1, W1",
        "beginning": "S1, W2",
        "behalf": "S3, W3",
        "behave": "S3, W3",
        "behaviour": "S2, W1",
        "behind": "S1, W1",
        "being": "S2, W3",
        "belief": "S3, W2",
        "believe": "S1, W1",
        "bell": "S2, W3",
        "belong": "S2, W2",
        "below": "S2, W2",
        "belt": "S2, W3",
        "bench": "S2, W3",
        "bend": "S3, W3",
        "beneath": "W2",
        "benefit": "S2, W1",
        "beside": "S3, W2",
        "best": "S1, W1",
        "bet": "S1",
        "better": "S1, W1",
        "between": "S1, W1",
        "beyond": "S2, W1",
        "bicycle": "W3",
        "bid": "W3",
        "big": "S1, W1",
        "bike": "S2",
        "bill": "S1, W1",
        "bin": "S2",
        "bird": "S2, W2",
        "birth": "S2, W2",
        "birthday": "S1, W3",
        "biscuit": "S2",
        "bit": "S1, W1",
        "bite": "S2",
        "bitter": "S3, W3",
        "black": "S1, W1",
        "blade": "S3",
        "blame": "S2, W3",
        "blank": "S3",
        "bless": "S3",
        "blind": "S2, W3",
        "block": "S2, W2",
        "bloke": "S2",
        "blonde": "S3",
        "blood": "S2, W1",
        "blow": "S2, W3",
        "blue": "S1, W2",
        "board": "S1, W1",
        "boat": "S1, W2",
        "body": "S1, W1",
        "boil": "S3",
        "boiler": "S3",
        "boiling": "S3",
        "bomb": "S3, W3",
        "bone": "S2, W2",
        "bonus": "S2",
        "book": "S1, W1",
        "boom": "S3",
        "boot": "S2, W3",
        "border": "S3, W2",
        "bored": "S3",
        "boring": "S2",
        "born": "S1, W2",
        "borrow": "S2, W3",
        "boss": "S2, W3",
        "both": "S1, W1",
        "bother": "S1, W3",
        "bottle": "S1, W2",
        "bottom": "S1, W3",
        "bounce": "S3",
        "bound": "S2, W3",
        "bowl": "S2, W3",
        "box": "S1, W1",
        "boy": "S1, W1",
        "boyfriend": "S3",
        "brain": "S2, W2",
        "branch": "S2, W2",
        "brave": "S3",
        "bread": "S2, W3",
        "break": "S2, W2",
        "breakfast": "S2, W2",
        "breast": "S3",
        "breath": "S3, W2",
        "breathe": "S3, W3",
        "brick": "S2, W3",
        "bridge": "S2, W2",
        "brief": "S2, W2",
        "briefly": "S2, W3",
        "bright": "S2, W2",
        "brilliant": "S2, W3",
        "bring": "S1, W1",
        "broad": "S2, W2",
        "brother": "S1, W1",
        "brown": "S2, W2",
        "brush": "S3",
        "buck": "S1",
        "bucket": "S2",
        "buddy": "S3",
        "budget": "S1, W2",
        "bug": "S3",
        "build": "S1, W1",
        "builder": "S3",
        "building": "S1, W1",
        "bump": "S3",
        "bunch": "S2",
        "burn": "S2, W3",
        "burst": "W3",
        "bury": "W3",
        "bus": "S1, W2",
        "business": "S1, W1",
        "busy": "S1, W2",
        "but": "S1, W1",
        "butcher": "S3",
        "butter": "S2",
        "button": "S2",
        "buy": "S1, W1",
        "buyer": "S3, W3",
        "by": "S1, W1",
        "bye": "S1",
        "cabinet": "S2, W2",
        "cable": "W3",
        "cake": "S2, W3",
        "calculate": "S2, W3",
        "calculation": "S2",
        "calculator": "S3",
        "calendar": "S3",
        "call": "S1, W1",
        "calm": "S3, W3",
        "camera": "S2, W3",
        "camp": "S3, W3",
        "campaign": "S2, W1",
        "can": "S1, W1",
        "cancel": "S2",
        "cancer": "S2, W2",
        "candidate": "W2",
        "candle": "S3",
        "candy": "S3",
        "cap": "S3",
        "capable": "S2, W2",
        "capacity": "S3, W2",
        "capital": "S3, W1",
        "captain": "W3",
        "capture": "W3",
        "car": "S1, W1",
        "card": "S1, W2",
        "care": "S1, W1",
        "career": "S2, W2",
        "careful": "S1, W2",
        "carefully": "S2, W2",
        "carpet": "S2, W3",
        "carrot": "S3",
        "carry": "S1, W1",
        "cartoon": "S3",
        "case": "S1, W1",
        "cash": "S2, W2",
        "cast": "W3",
        "castle": "W3",
        "cat": "S1, W3",
        "catalogue": "W3",
        "catch": "S1, W1",
        "category": "S2, W2",
        "cause": "S1, W1",
        "CD": "S3, W3",
        "cease": "W3",
        "ceiling": "S3, W3",
        "celebrate": "W3",
        "celebration": "S3",
        "cell": "S3, W2",
        "cellphone": "S2, W3",
        "cent": "S1, W1",
        "centimetre": "S3, W3",
        "central": "S1, W1",
        "centre": "S1, W1",
        "century": "S2, W1",
        "cereal": "S3",
        "certain": "S1, W1",
        "certainly": "S1, W1",
        "certificate": "S3, W3",
        "chain": "S3, W2",
        "chair": "S1, W2",
        "chairman": "S3, W1",
        "challenge": "S2, W2",
        "champion": "W3",
        "championship": "W3",
        "chance": "S1, W1",
        "change": "S1, W1",
        "channel": "S3, W2",
        "chap": "S2",
        "chapter": "S3, W1",
        "character": "S1, W1",
        "characteristic": "S3, W2",
        "characterize": "W3",
        "charge": "S1, W1",
        "charity": "S3, W3",
        "chart": "S3, W3",
        "chase": "S3",
        "chat": "S2",
        "cheap": "S1, W2",
        "cheat": "S3",
        "check": "S1, W2",
        "cheek": "W3",
        "cheese": "S2, W3",
        "chemical": "W3",
        "chemist": "S3",
        "chemistry": "S2",
        "cheque": "S2",
        "cherry": "S3",
        "chest": "S2, W3",
        "chicken": "S2",
        "chief": "S2, W2",
        "child": "S1, W1",
        "childhood": "W3",
        "chip": "S2, W3",
        "chocolate": "S2",
        "choice": "S1, W1",
        "choose": "S1, W1",
        "chop": "S3",
        "chuck": "S3",
        "church": "S1, W1",
        "cigarette": "S2, W3",
        "cinema": "S3",
        "circle": "S2, W2",
        "circuit": "W3",
        "circumstance": "S2, W1",
        "citizen": "S2, W2",
        "city": "S1, W1",
        "civil": "S3, W2",
        "claim": "S2, W1",
        "class": "S1, W1",
        "classic": "W3",
        "classical": "W3",
        "classroom": "S3, W3",
        "clean": "S2, W2",
        "cleaner": "S3",
        "clear": "S1, W1",
        "clearly": "S1, W1",
        "clerk": "S3",
        "clever": "S2",
        "click": "S3",
        "client": "S2, W1",
        "climate": "W3",
        "climb": "W2",
        "clock": "S2, W3",
        "close": "S1, W1",
        "closed": "S3",
        "closely": "S3, W2",
        "closet": "S3",
        "cloth": "S3",
        "clothes": "S2, W2",
        "cloud": "S3, W3",
        "club": "S1, W1",
        "clue": "S2",
        "coach": "S3, W2",
        "coal": "S2, W2",
        "coast": "S3, W2",
        "coat": "S2, W3",
        "code": "S2, W2",
        "coffee": "S1, W2",
        "coin": "S3",
        "cold": "S1, W1",
        "collapse": "S3",
        "collar": "S3",
        "colleague": "S2, W2",
        "collect": "S1, W2",
        "collection": "S2, W1",
        "college": "S1, W2",
        "colour": "S1, W1",
        "column": "S3, W2",
        "combination": "S3, W2",
        "combine": "S3, W2",
        "come": "S1, W1",
        "comfort": "W3",
        "comfortable": "S2, W3",
        "command": "W3",
        "comment": "S1, W2",
        "commercial": "S3, W2",
        "commission": "S3, W2",
        "commit": "S2, W2",
        "commitment": "S2, W2",
        "committee": "S3, W1",
        "common": "S1, W1",
        "communicate": "S3, W3",
        "communication": "S2, W1",
        "community": "S1, W1",
        "company": "S1, W1",
        "compare": "S1, W1",
        "comparison": "S3, W2",
        "compete": "S3, W3",
        "competition": "S2, W1",
        "competitive": "S3, W3",
        "complain": "S2, W3",
        "complaint": "S3, W3",
        "complete": "S2, W1",
        "completely": "S1, W2",
        "complex": "S3, W2",
        "complicated": "S2",
        "component": "W2",
        "comprehensive": "W3",
        "comprise": "W3",
        "computer": "S1, W1",
        "concentrate": "S2, W2",
        "concentration": "S3, W2",
        "concept": "S3, W2",
        "concern": "S1, W1",
        "concerned": "S1, W1",
        "concerning": "W3",
        "concert": "S3, W3",
        "conclude": "S3, W2",
        "conclusion": "S3, W2",
        "condition": "S2, W1",
        "conduct": "W3",
        "conference": "S2, W1",
        "confidence": "S2, W2",
        "confident": "S3, W3",
        "confine": "W3",
        "confirm": "S2, W2",
        "conflict": "S3, W2",
        "confused": "S3",
        "confusing": "S3",
        "confusion": "S3, W3",
        "congratulation": "S3",
        "connect": "S2, W2",
        "connection": "S3, W2",
        "conscious": "S2, W3",
        "consciousness": "W3",
        "consent": "W3",
        "consequence": "S3, W2",
        "consider": "S1, W1",
        "considerable": "S3, W1",
        "considerably": "S3",
        "consideration": "S2, W2",
        "consist": "W3",
        "consistent": "S3, W3",
        "constant": "S3, W3",
        "constantly": "S3, W3",
        "constitute": "W3",
        "construct": "W3",
        "construction": "S3, W2",
        "consult": "S3, W3",
        "consumer": "S3, W2",
        "consumption": "W3",
        "contact": "S2, W2",
        "contain": "S2, W1",
        "contemporary": "W2",
        "content": "S3, W2",
        "contest": "W3",
        "context": "S2, W2",
        "continue": "S1, W1",
        "continuous": "S3, W3",
        "contract": "S1, W1",
        "contrast": "W2",
        "contribute": "S3, W2",
        "contribution": "S2, W2",
        "control": "S1, W1",
        "convenient": "S3",
        "convention": "W2",
        "conventional": "W3",
        "conversation": "S1, W2",
        "convert": "W3",
        "conviction": "W3",
        "convince": "S3, W3",
        "cook": "S1, W3",
        "cooker": "S3",
        "cookie": "S3, W3",
        "cool": "S2, W3",
        "cooperation": "S3, W3",
        "cope": "S2, W3",
        "copy": "S1, W2",
        "core": "W3",
        "corn": "S3",
        "corner": "S1, W2",
        "correct": "S1, W2",
        "corridor": "S3, W3",
        "cost": "S1, W1",
        "cottage": "S3, W3",
        "cotton": "W3",
        "could": "S1, W1",
        "council": "S2, W2",
        "count": "S2, W3",
        "counter": "S3",
        "country": "S1, W1",
        "countryside": "S3, W3",
        "county": "W2",
        "couple": "S1, W1",
        "courage": "S3",
        "course": "S1, W1",
        "court": "S1, W1",
        "cousin": "S2",
        "cover": "S1, W2",
        "cow": "S2",
        "crack": "S3",
        "craft": "W3",
        "crash": "S3",
        "crazy": "S2",
        "create": "S2, W1",
        "creation": "W2",
        "creative": "W3",
        "creature": "W3",
        "credit": "S2, W2",
        "crew": "S3, W3",
        "crime": "S2, W2",
        "criminal": "S3, W2",
        "crisis": "S3, W2",
        "criterion": "W2",
        "critic": "W3",
        "critical": "S3, W2",
        "criticism": "S3, W2",
        "criticize": "W3",
        "crop": "W3",
        "cross": "S2, W2",
        "crowd": "S3, W2",
        "crown": "W3",
        "crucial": "W2",
        "cruel": "S3",
        "cry": "W3",
        "cultural": "W2",
        "culture": "S2, W1",
        "cup": "S1, W1",
        "cupboard": "S2",
        "curious": "S3",
        "currency": "W2",
        "current": "S2, W2",
        "currently": "S2, W2",
        "curtain": "S3, W3",
        "curve": "S3, W3",
        "cushion": "S3",
        "custom": "W3",
        "customer": "S1, W1",
        "cut": "S2, W2",
        "cute": "S2",
        "cycle": "S3, W3",
        "dad": "S1, W3",
        "daddy": "S1",
        "daft": "S3",
        "daily": "S3, W2",
        "damage": "S3, W2",
        "dance": "S2, W3",
        "danger": "S2, W2",
        "dangerous": "S2, W2",
        "dare": "S3, W3",
        "dark": "S2, W1",
        "darkness": "W3",
        "darling": "S2",
        "data": "S1, W1",
        "database": "S3, W3",
        "date": "S1, W1",
        "daughter": "S1, W1",
        "day": "S1, W1",
        "dead": "S1, W1",
        "deaf": "W3",
        "deal": "S1, W1",
        "dealer": "W3",
        "dear": "S2, W2",
        "death": "S1, W1",
        "debate": "S2, W2",
        "debt": "S3, W2",
        "decade": "W2",
        "decent": "S3",
        "decide": "S1, W1",
        "decision": "S1, W1",
        "declare": "W2",
        "decline": "W2",
        "deep": "S2, W1",
        "deeply": "W3",
        "defeat": "W3",
        "defence": "S2, W1",
        "defend": "S3, W3",
        "define": "S2, W2",
        "definite": "S3",
        "definitely": "S1",
        "definition": "S2, W2",
        "degree": "S2, W1",
        "delay": "W3",
        "deliberately": "S3",
        "deliver": "S2, W2",
        "delivery": "S3, W3",
        "demand": "S2, W1",
        "democracy": "W2",
        "democratic": "W2",
        "demonstrate": "S3, W2",
        "demonstration": "W3",
        "dentist": "S3",
        "deny": "S3, W2",
        "department": "S2, W1",
        "departure": "W3",
        "depend": "S1, W2",
        "dependent": "W3",
        "deposit": "S3, W3",
        "depression": "W3",
        "depth": "S3, W3",
        "derive": "W3",
        "describe": "S2, W1",
        "description": "S2, W2",
        "desert": "W3",
        "deserve": "S3, W3",
        "design": "S2, W1",
        "designer": "W3",
        "desire": "W2",
        "desk": "S2, W2",
        "desperate": "S3, W3",
        "despite": "S3, W1",
        "destroy": "S2, W2",
        "destruction": "W3",
        "detail": "S2, W1",
        "detailed": "W2",
        "detect": "W3",
        "determination": "W3",
        "determine": "W2",
        "determined": "W3",
        "develop": "S2, W1",
        "development": "S1, W1",
        "device": "S3, W2",
        "devil": "S3",
        "diagram": "S3",
        "diamond": "S3",
        "diary": "S3",
        "die": "S1, W1",
        "diet": "S3, W2",
        "differ": "W3",
        "difference": "S1, W1",
        "different": "S1, W1",
        "difficult": "S1, W1",
        "difficulty": "S2, W1",
        "dig": "S2",
        "dimension": "W3",
        "dinner": "S1, W2",
        "direct": "S2, W1",
        "direction": "S1, W1",
        "directly": "S2, W2",
        "director": "S2, W1",
        "directory": "S3",
        "dirt": "S3",
        "dirty": "S2, W3",
        "disabled": "S3, W3",
        "disagree": "S3",
        "disappear": "S2, W2",
        "disappoint": "W3",
        "disappointed": "S3, W3",
        "disaster": "S3, W3",
        "disc": "S2, W3",
        "discipline": "S3, W3",
        "discount": "S3",
        "discover": "S2, W1",
        "discovery": "W3",
        "discuss": "S2, W1",
        "discussion": "S2, W1",
        "disease": "S3, W1",
        "disgusting": "S2",
        "dish": "S2, W3",
        "disk": "S2, W3",
        "dismiss": "W3",
        "display": "S3, W2",
        "dispute": "W2",
        "distance": "S2, W2",
        "distant": "W3",
        "distinct": "W3",
        "distinction": "W3",
        "distinguish": "S3, W3",
        "distribute": "W2",
        "distribution": "W2",
        "district": "S3, W2",
        "disturb": "W3",
        "divide": "S2, W2",
        "division": "S3, W1",
        "divorce": "S3",
        "do": "S1, W1",
        "doctor": "S1, W1",
        "document": "S2, W2",
        "dog": "S1, W1",
        "dollar": "S1, W2",
        "domestic": "W2",
        "dominant": "W3",
        "dominate": "W3",
        "door": "S1, W1",
        "dot": "S2",
        "double": "S1, W2",
        "doubt": "S1, W1",
        "down": "S1, W1",
        "downstairs": "S2",
        "downtown": "S3, W3",
        "dozen number": "S2, W3",
        "draft": "S2, W3",
        "drag": "S3, W3",
        "drama": "W3",
        "dramatic": "W3",
        "draw": "S3",
        "drawer": "S3",
        "drawing": "S3, W3",
        "dream": "S2, W2",
        "dress": "S2, W2",
        "drink": "S1, W2",
        "drive": "S2, W2",
        "driver": "S1, W2",
        "drop": "S2, W3",
        "drug": "S2, W1",
        "drunk": "S3",
        "dry": "S2, W2",
        "duck": "S3",
        "dude": "S3",
        "due": "S1, W1",
        "dull": "S3",
        "dumb": "S3",
        "dump": "S3",
        "during": "S1, W1",
        "dust": "S3, W3",
        "duty": "S2, W1",
        "DVD": "S3, W3",
        "each": "S1, W1",
        "ear": "S2, W2",
        "early": "S1, W1",
        "earn": "S2, W2",
        "earth": "S2, W2",
        "ease": "W3",
        "easily": "S2, W1",
        "east": "S1, W2",
        "eastern": "S2, W2",
        "easy": "S1, W1",
        "eat": "S1, W1",
        "economic": "S2, W1",
        "economics": "W3",
        "economy": "S2, W1",
        "edge": "S2, W2",
        "edition": "W3",
        "editor": "W2",
        "education": "S1, W1",
        "educational": "S3, W2",
        "effect": "S1, W1",
        "effective": "S2, W1",
        "effectively": "S3, W2",
        "efficiency": "W3",
        "efficient": "S3, W3",
        "effort": "S1, W1",
        "egg": "S1, W2",
        "either": "S1, W1",
        "elderly": "S3, W2",
        "elect": "S3, W3",
        "election": "S2, W1",
        "electric": "S2, W3",
        "electrical": "S3",
        "electricity": "S2, W3",
        "electronic": "S3, W3",
        "element": "S2, W1",
        "elevator": "S3, W3",
        "else": "S1, W1",
        "elsewhere": "S3, W2",
        "email": "S2, W2",
        "embarrassed": "S3",
        "emerge": "W2",
        "emergency": "S3, W3",
        "emotion": "W3",
        "emotional": "S3, W3",
        "emphasis": "S3, W2",
        "emphasize": "S3, W2",
        "empire": "W3",
        "employ": "S3, W2",
        "employee": "S2, W2",
        "employer": "S2, W2",
        "employment": "S2, W1",
        "empty": "S2, W2",
        "enable": "S3, W1",
        "encounter": "W3",
        "encourage": "S2, W1",
        "encouraging": "S3",
        "end": "S1, W1",
        "enemy": "W2",
        "energy": "S2, W1",
        "engage": "W3",
        "engine": "S2, W2",
        "engineer": "S3, W3",
        "engineering": "S3, W3",
        "enhance": "W3",
        "enjoy": "S1, W1",
        "enjoyable": "S3",
        "enormous": "S2, W3",
        "enough": "S1, W1",
        "enquiry": "S2, W2",
        "ensure": "S2, W1",
        "enter": "S2, W1",
        "enterprise": "W2",
        "entertainment": "S3, W3",
        "enthusiasm": "W3",
        "enthusiastic": "S3",
        "entire": "S3, W2",
        "entirely": "S2, W2",
        "entitle": "S3, W3",
        "entrance": "S3, W3",
        "entry": "S3, W2",
        "envelope": "S3",
        "environment": "S1, W1",
        "environmental": "S2, W2",
        "equal": "S1, W2",
        "equally": "S3, W2",
        "equipment": "S2, W2",
        "equivalent": "W3",
        "era": "W3",
        "error": "S3, W2",
        "escape": "S3",
        "especially": "S1, W1",
        "essay": "S3",
        "essential": "S3, W2",
        "essentially": "S2, W3",
        "establish": "S2, W1",
        "establishment": "W2",
        "estate": "S2, W2",
        "estimate": "S3, W2",
        "ethnic": "W3",
        "even": "S1, W1",
        "evening": "S1, W1",
        "event": "S1, W1",
        "eventually": "S1, W2",
        "ever": "S1, W1",
        "every": "S1, W1",
        "everybody": "S1, W3",
        "everyone": "S1, W1",
        "everything": "S1, W1",
        "everywhere": "S2, W3",
        "evidence": "S2, W1",
        "evil": "S3, W3",
        "exact": "S3",
        "exactly": "S1, W2",
        "exam": "S1",
        "examination": "W2",
        "examine": "S3, W2",
        "example": "S1, W1",
        "excellent": "S1, W2",
        "except": "S2, W2",
        "exception": "S3, W2",
        "exchange": "S2, W1",
        "excitement": "S3, W3",
        "exciting": "S2, W3",
        "exclude": "W3",
        "excuse": "S3",
        "executive": "W3",
        "exercise": "S2, W2",
        "exhibition": "W2",
        "exist": "S2, W1",
        "existence": "S3, W2",
        "existing": "S2, W2",
        "exit": "S3",
        "expand": "S3, W3",
        "expansion": "W3",
        "expect": "S1, W1",
        "expectation": "S3, W2",
        "expenditure": "W3",
        "expense": "S3, W2",
        "expensive": "S1, W2",
        "experience": "S1, W1",
        "experienced": "S3",
        "experiment": "S3, W2",
        "experimental": "W3",
        "expert": "W3",
        "explain": "S1, W1",
        "explanation": "S3, W2",
        "explore": "S3, W2",
        "explosion": "W3",
        "export": "W2",
        "expose": "W3",
        "express": "S2, W1",
        "expression": "S2, W2",
        "extend": "S3, W2",
        "extension": "S3, W3",
        "extensive": "W3",
        "extent": "S2, W1",
        "external": "W2",
        "extra": "S1, W2",
        "extraordinary": "S3, W3",
        "extreme": "S3, W3",
        "extremely": "S2, W2",
        "eye": "S1, W1",
        "face": "S1, W1",
        "facility": "S2, W1",
        "fact": "S1, W1",
        "factor": "S3, W1",
        "factory": "S2, W2",
        "fail": "S2, W1",
        "failure": "S3, W2",
        "fair": "S1, W2",
        "fairly": "S1, W2",
        "faith": "S3, W2",
        "fall": "S2, W2",
        "false": "W3",
        "familiar": "S3, W2",
        "family": "S1, W1",
        "famous": "S2, W2",
        "fan": "S3, W2",
        "fancy": "S3",
        "fantastic": "S3",
        "far": "S1, W1",
        "farm": "S2, W2",
        "farmer": "S2, W2",
        "fascinating": "S3",
        "fashion": "S3, W2",
        "fast": "S2, W2",
        "fat": "S2, W3",
        "father": "S1, W1",
        "fault": "S2, W3",
        "favour": "S2, W3",
        "favourite": "S3, W3",
        "fear": "S3, W1",
        "feature": "S2, W1",
        "federal": "W1",
        "fee": "S3, W3",
        "feed": "S1, W2",
        "feedback": "S3",
        "feel": "S1, W1",
        "feeling": "S1, W1",
        "fellow": "W3",
        "female": "S3, W2",
        "fence": "S3",
        "festival": "S3, W3",
        "fetch": "S3",
        "few": "S1, W1",
        "field": "S1, W1",
        "fight": "S2, W3",
        "figure": "S1, W1",
        "file": "S1, W2",
        "fill": "S1, W1",
        "film": "S1, W1",
        "filthy": "S3",
        "final": "S1, W1",
        "finally": "S2, W1",
        "finance": "S3, W2",
        "financial": "S2, W1",
        "find": "S1, W1",
        "finding": "W2",
        "fine": "S1, W1",
        "finger": "S2, W2",
        "finish": "S3",
        "fire": "S1, W1",
        "firm": "S3, W2",
        "first": "S1, W1",
        "firstly": "S3",
        "fish": "S1, W1",
        "fishing": "S3",
        "fit": "S2, W3",
        "fix": "S2, W2",
        "fixed": "S3, W3",
        "flash": "S3",
        "flat": "S2, W2",
        "flavour": "W3",
        "flesh": "W3",
        "flight": "S3, W2",
        "flood": "W3",
        "floor": "S1, W1",
        "flow": "S3, W2",
        "flower": "S2, W2",
        "fly": "S2, W2",
        "focus": "S3, W2",
        "fold": "W3",
        "folk": "S2, W3",
        "follow": "S1, W1",
        "following": "S3, W1",
        "food": "S1, W1",
        "foot": "S1, W1",
        "football": "S1, W2",
        "for": "S1, W1",
        "force": "S2, W1",
        "foreign": "S3, W1",
        "forest": "S2, W2",
        "forever": "S2, W3",
        "forget": "S1, W1",
        "forgive": "S3",
        "fork": "S3",
        "form": "S1, W1",
        "formal": "S2, W2",
        "formally": "S3",
        "formation": "W3",
        "former": "S2, W1",
        "formula": "S3, W3",
        "forth": "S2",
        "fortnight": "S3",
        "fortunate": "S3",
        "fortune": "S3, W3",
        "forward": "S2, W3",
        "foundation": "W2",
        "frame": "S3, W3",
        "frankly": "S3",
        "free": "S1, W1",
        "freedom": "S3, W2",
        "freeway": "S2, W3",
        "freeze": "S3, W3",
        "freezer": "S3",
        "frequent": "W3",
        "frequently": "S3, W2",
        "fresh": "S2, W2",
        "fridge": "S2",
        "friend": "S1, W1",
        "friendly": "S2, W3",
        "friendship": "W3",
        "frightened": "S3",
        "from": "S1, W1",
        "front": "S1, W2",
        "fruit": "S2, W3",
        "fry": "S3",
        "fuel": "S3, W2",
        "fulfil": "W3",
        "full": "S1, W1",
        "fully": "S2, W2",
        "fun": "S2, W3",
        "function": "S3, W1",
        "fund": "S3, W1",
        "fundamental": "W2",
        "funeral": "S3",
        "funny": "S1, W3",
        "furniture": "S2, W3",
        "further": "S1, W1",
        "fuss": "S3",
        "future": "S1, W1",
        "gain": "W3",
        "gallery": "W3",
        "game": "S1, W1",
        "gang": "S3",
        "gap": "S2, W2",
        "garage": "S2",
        "garbage": "S3",
        "garden": "S1, W1",
        "garlic": "S3",
        "gas": "S1, W2",
        "gasoline": "S3, W3",
        "gate": "S2, W2",
        "gather": "S3, W2",
        "gay": "S3, W3",
        "gear": "S3",
        "gene": "S3, W3",
        "general": "S1, W1",
        "generally": "S2, W1",
        "generate": "S3, W2",
        "generation": "S3, W2",
        "generous": "W3",
        "gentle": "S3, W3",
        "gentleman": "S2, W2",
        "gently": "W3",
        "genuine": "S3, W3",
        "get": "S1, W1",
        "giant": "W3",
        "gift": "S2, W2",
        "girl": "S1, W1",
        "girlfriend": "S3",
        "give": "S1, W1",
        "glad": "S2, W3",
        "glance": "W3",
        "glass": "S1, W1",
        "global": "W2",
        "glove": "S3",
        "go": "S1",
        "goal": "S2, W1",
        "god": "S1, W1",
        "gold": "S3, W3",
        "golden": "W3",
        "golf": "S2, W3",
        "good": "S1, W1",
        "good night": "S3",
        "goodbye": "S3",
        "goodness": "S2",
        "goods": "S2, W2",
        "gorgeous": "S3",
        "gosh": "S2",
        "govern": "W3",
        "government": "S2, W1",
        "governor": "W3",
        "grab": "S2, W3",
        "grade": "S2, W3",
        "gradually": "S3, W3",
        "gram": "S3",
        "grammar": "S3, W3",
        "grand": "S2, W3",
        "grandad": "S3",
        "grandfather": "S3",
        "grandma": "S2",
        "grandmother": "S3",
        "grandpa": "S3",
        "granny": "S3",
        "grant": "S2, W2",
        "graph": "S3",
        "grass": "S2, W2",
        "grateful": "S3, W3",
        "great": "S1, W1",
        "greatly": "W3",
        "green": "S1, W2",
        "grey": "S2, W2",
        "grocery": "S3",
        "gross": "S3",
        "ground": "S1, W1",
        "group": "S1, W1",
        "grow": "S1, W1",
        "growth": "S3, W1",
        "guarantee": "S3",
        "guard": "S3, W3",
        "guess": "S3",
        "guest": "S3, W2",
        "guidance": "S3, W3",
        "guide": "S3, W2",
        "guilty": "S2, W3",
        "guitar": "S3, W3",
        "gun": "S2, W2",
        "guy": "S1, W3",
        "habit": "S3, W3",
        "hair": "S1, W1",
        "half": "S1, W1",
        "halfway": "S3",
        "hall": "S2, W2",
        "hand": "S1, W1",
        "handbag": "S3",
        "handle": "S3",
        "handy": "S3",
        "hang": "S1, W2",
        "happen": "S1, W1",
        "happy": "S1, W1",
        "hard": "S1, W1",
        "hardly": "S2, W2",
        "harm": "S3, W3",
        "hat": "S1, W3",
        "hate": "S1, W3",
        "have": "S1, W1",
        "he": "S1, W1",
        "head": "S1, W1",
        "headquarters": "W3",
        "health": "S1, W1",
        "healthy": "S3, W3",
        "hear": "S1, W1",
        "hearing": "S3, W2",
        "heart": "S1, W1",
        "heat": "S2, W2",
        "heater": "S3",
        "heating": "S3",
        "heaven": "S3, W3",
        "heavily": "W3",
        "heavy": "S1, W1",
        "height": "S2, W3",
        "hell": "S1, W3",
        "hello": "S1",
        "help": "S1, W1",
        "helpful": "S2, W3",
        "hence": "W3",
        "her": "S1, W1",
        "here": "S1, W1",
        "hero": "W3",
        "hers": "S3, W3",
        "herself": "S2, W1",
        "hesitate": "W3",
        "hi": "S1",
        "hide": "S2, W2",
        "high": "S1, W1",
        "highlight": "W3",
        "highly": "S2, W2",
        "highway": "S3",
        "hill": "S2, W2",
        "him": "S1, W1",
        "himself": "S1, W1",
        "hire": "S2, W3",
        "his": "S1, W1",
        "historian": "W3",
        "historical": "W2",
        "history": "S2, W1",
        "hit": "S3, W3",
        "hold": "S2, W3",
        "holder": "W2",
        "holding": "W3",
        "hole": "S1, W2",
        "holiday": "S1, W2",
        "holy": "W3",
        "home": "S1, W1",
        "homework": "S2",
        "honest": "S1, W3",
        "honestly": "S2",
        "honey": "S2",
        "honour": "W3",
        "hook": "S3",
        "hope": "S2, W2",
        "hopefully": "S1",
        "hopeless": "S3",
        "horrible": "S2",
        "horror": "W3",
        "horse": "S1, W1",
        "hospital": "S1, W1",
        "host": "W3",
        "hot": "S1, W2",
        "hotel": "S2, W1",
        "hour": "S1, W1",
        "house": "S1, W1",
        "household": "S3, W2",
        "housing": "W2",
        "how": "S1, W1",
        "however": "S1, W1",
        "huge": "S1, W2",
        "human": "S2, W1",
        "hungry": "S2",
        "hunt": "W3",
        "hurry": "S3",
        "hurt": "S1, W2",
        "husband": "S1, W1",
        "I": "S1, W1",
        "ice": "S2, W3",
        "idea": "S1, W1",
        "ideal": "S3, W3",
        "ideally": "S3",
        "identify": "S2, W1",
        "identity": "W2",
        "idiot": "S3",
        "if": "S1, W1",
        "ignore": "S2, W2",
        "ill": "S3, W2",
        "illegal": "W3",
        "illness": "S3, W3",
        "illustrate": "W2",
        "image": "S2, W1",
        "imagination": "S3, W3",
        "imagine": "S1, W2",
        "immediate": "S3, W2",
        "immediately": "S2, W1",
        "impact": "S3, W2",
        "implement": "W3",
        "implication": "S3, W2",
        "imply": "W2",
        "import": "W3",
        "importance": "S3, W1",
        "important": "S1, W1",
        "impose": "S3, W2",
        "impossible": "S2, W2",
        "impress": "S3, W3",
        "impression": "S2, W2",
        "impressive": "W3",
        "improve": "S2, W1",
        "improvement": "S3, W2",
        "in": "S1, W1",
        "inch": "S2, W3",
        "incident": "S3, W2",
        "include": "S1, W1",
        "including": "S2, W1",
        "income": "S2, W1",
        "incorporate": "W3",
        "increase": "S2, W1",
        "increasingly": "W2",
        "incredible": "S3",
        "incredibly": "S3",
        "indeed": "S1, W1",
        "independence": "W2",
        "independent": "S2, W2",
        "index": "W2",
        "indicate": "S3, W1",
        "indication": "S3, W3",
        "individual": "S2, W1",
        "industrial": "S3, W1",
        "industry": "S2, W1",
        "inevitable": "W3",
        "inevitably": "W3",
        "infant": "W3",
        "infection": "W3",
        "inflation": "S3, W2",
        "influence": "S3, W1",
        "inform": "S3, W3",
        "informal": "W3",
        "information": "S1, W1",
        "initial": "S3, W2",
        "initially": "S3, W3",
        "initiative": "S3, W2",
        "injure": "W3",
        "injury": "S3, W2",
        "inner": "S3, W2",
        "innocent": "W3",
        "innovation": "W3",
        "input": "W3",
        "inquiry": "W2",
        "insect": "W3",
        "inside": "S2, W2",
        "insist": "S3, W2",
        "inspection": "W3",
        "inspector": "S3, W3",
        "install": "W3",
        "instance": "S3, W2",
        "instant": "S3",
        "instead": "S1, W1",
        "institute": "W3",
        "institution": "W1",
        "instruction": "S3, W2",
        "instrument": "W2",
        "insurance": "S2, W2",
        "intellectual": "W3",
        "intelligence": "S3, W3",
        "intelligent": "S3",
        "intend": "S2, W1",
        "intense": "W3",
        "intention": "S3, W2",
        "interaction": "W3",
        "interest": "S1, W1",
        "interested": "S1, W2",
        "interesting": "S1, W2",
        "internal": "W2",
        "international": "S2, W1",
        "internet": "S2, W2",
        "interpret": "W3",
        "interpretation": "W2",
        "interval": "W3",
        "intervention": "W3",
        "interview": "S2, W2",
        "into": "S1, W1",
        "introduce": "S2, W1",
        "introduction": "S3, W2",
        "invest": "S3, W3",
        "investigate": "W2",
        "investigation": "W2",
        "investment": "S2, W1",
        "invite": "S2, W2",
        "involve": "S2, W1",
        "involved": "S2, W3",
        "involvement": "W3",
        "iron": "S2, W3",
        "island": "S3, W2",
        "issue": "S1, W1",
        "it": "S1, W1",
        "item": "S3, W2",
        "its": "S1, W1",
        "itself": "S1, W1",
        "jacket": "S2, W3",
        "jam": "S3",
        "job": "S1, W1",
        "join": "S1, W1",
        "joint": "S2, W2",
        "joke": "S2, W3",
        "journalist": "W3",
        "journey": "S3, W2",
        "joy": "W3",
        "judge": "S2, W2",
        "judgment": "W2",
        "juice": "S2",
        "jump": "S3",
        "jumper": "S3",
        "junior": "W3",
        "jury": "S3, W3",
        "just": "S1, W1",
        "justice": "W2",
        "justify": "S3, W3",
        "keen": "S3, W3",
        "keep": "S1, W1",
        "kettle": "S3",
        "key": "S3, W2",
        "keyboard": "S3",
        "kick": "S3",
        "kid": "S1, W2",
        "kill": "S1, W1",
        "kilometre": "S3, W3",
        "kind": "S2, W3",
        "king": "W1",
        "kiss": "S3, W3",
        "kit": "S3",
        "kitchen": "S1, W2",
        "knee": "S2, W2",
        "knife": "S3, W3",
        "knock": "S1, W3",
        "know": "S1, W1",
        "knowledge": "S2, W1",
        "known": "W3",
        "lab": "S3",
        "label": "S3, W3",
        "laboratory": "W3",
        "labour": "S2, W1",
        "lack": "S3, W2",
        "lad": "S2, W3",
        "ladder": "S3",
        "lady": "S1, W2",
        "lake": "S3, W3",
        "lamb": "S3",
        "lamp": "S3",
        "land": "S1, W1",
        "landlord": "W3",
        "landscape": "W3",
        "lane": "S3, W3",
        "language": "S1, W1",
        "large": "S1, W1",
        "largely": "S3, W2",
        "last": "S1, W1",
        "late": "S1, W1",
        "later": "S1, W1",
        "latter": "W2",
        "laugh": "S2, W2",
        "launch": "W2",
        "law": "S1, W1",
        "lawyer": "S3, W2",
        "lay": "S1, W2",
        "layer": "S3, W3",
        "lazy": "S3",
        "lead": "S1, W1",
        "leader": "S2, W1",
        "leadership": "S3, W2",
        "leading": "W2",
        "leaf": "S2, W2",
        "league": "W2",
        "lean": "S3",
        "learn": "S1, W1",
        "least": "S1, W1",
        "leather": "W3",
        "leave": "S1, W1",
        "lecture": "S2, W3",
        "left": "S1, W1",
        "leg": "S1, W1",
        "legal": "S2, W1",
        "legislation": "W2",
        "leisure": "W3",
        "lend": "S3, W3",
        "length": "S2, W2",
        "less": "S1, W1",
        "lesson": "S2, W3",
        "let": "S1, W1",
        "letter": "S1, W1",
        "level": "S1, W2",
        "liberal": "W2",
        "library": "S2, W1",
        "licence": "S3, W2",
        "lick": "S3",
        "lid": "S3",
        "lie": "S2, W1",
        "life": "S1, W1",
        "lift": "S2, W2",
        "light": "S1, W1",
        "lighting": "S3",
        "like": "S1, W1",
        "likely": "S1, W1",
        "limit": "S2, W2",
        "limitation": "W3",
        "limited": "W2",
        "line": "S1, W1",
        "link": "S3, W2",
        "lip": "S3, W2",
        "liquid": "W3",
        "list": "S1, W1",
        "listen": "S1, W1",
        "literally": "S2",
        "literary": "W2",
        "literature": "S3, W2",
        "little": "S1, W1",
        "live": "S1, W1",
        "lively": "S3",
        "living": "S2",
        "load": "S1, W3",
        "loan": "S2, W2",
        "local": "S1, W1",
        "locate": "W3",
        "location": "S3, W2",
        "lock": "S2",
        "log": "S3",
        "logical": "S3",
        "lonely": "S3",
        "long": "S1, W1",
        "long-term": "W3",
        "look": "S1, W1",
        "loose": "S3, W3",
        "lord": "S3, W2",
        "lorry": "S3",
        "lose": "S1, W1",
        "loss": "S2, W1",
        "lost": "S2, W3",
        "lot": "S1, W1",
        "loud": "S2, W3",
        "lounge": "S3",
        "love": "S1, W1",
        "lovely": "S1, W3",
        "lover": "W3",
        "low": "S1, W1",
        "lower": "S3, W3",
        "luck": "S2, W3",
        "luckily": "S3",
        "lucky": "S2, W3",
        "lump": "S2",
        "lunch": "S1, W2",
        "lunchtime": "S3",
        "machine": "S1, W1",
        "machinery": "W3",
        "mad": "S2, W3",
        "madam": "S3",
        "magazine": "S2, W2",
        "magic": "W3",
        "mail": "S3, W3",
        "main": "S1, W1",
        "mainly": "S2, W2",
        "maintain": "S2, W1",
        "maintenance": "W3",
        "major": "S1, W1",
        "majority": "S2, W1",
        "make": "S1, W1",
        "male": "S3, W2",
        "mall": "S3, W3",
        "man": "S1, W1",
        "manage": "S1, W1",
        "management": "S1, W1",
        "manager": "S1, W1",
        "manner": "S3, W2",
        "manufacturer": "W2",
        "manufacturing": "W3",
        "many": "S1, W1",
        "map": "S2, W2",
        "march": "W2",
        "margin": "W3",
        "mark": "S3, W2",
        "market": "S1, W1",
        "marketing": "S3, W3",
        "marriage": "S2, W2",
        "married": "S2, W2",
        "marry": "S1, W2",
        "marvellous": "S2",
        "mass": "W2",
        "massive": "S2, W3",
        "master": "S2, W2",
        "match": "S2, W2",
        "mate": "S2",
        "material": "S1, W1",
        "math": "S2",
        "maths": "S2",
        "matter": "S1, W1",
        "maximum": "S3, W3",
        "may": "S1, W1",
        "maybe": "S1, W1",
        "me": "S1, W1",
        "meal": "S2, W2",
        "mean": "S1, W1",
        "meaning": "S2, W1",
        "means": "S2, W2",
        "meanwhile": "W2",
        "measure": "S2, W2",
        "measurement": "W3",
        "meat": "S2, W3",
        "mechanism": "S3, W3",
        "media": "S2, W2",
        "medical": "S2, W2",
        "medicine": "S2, W3",
        "medieval": "W3",
        "medium": "S3",
        "meet": "S1, W1",
        "meeting": "S1, W1",
        "member": "S1, W1",
        "membership": "S2, W2",
        "memory": "S2, W1",
        "mental": "S2, W2",
        "mention": "S1, W1",
        "menu": "S3",
        "mere": "W3",
        "merely": "S3, W2",
        "mess": "S2",
        "message": "S1, W2",
        "messy": "S3",
        "metal": "S2, W2",
        "method": "S1, W1",
        "metre": "S2, W3",
        "middle": "S1, W2",
        "midnight": "S3",
        "might": "S1, W1",
        "mile": "S1, W1",
        "military": "S2, W1",
        "milk": "S2, W3",
        "millimetre": "S3",
        "mind": "S1, W1",
        "mine": "S2, W3",
        "mineral": "W3",
        "minimum": "S2, W3",
        "minister": "S1, W1",
        "ministry": "W2",
        "minor": "S2, W2",
        "minority": "S3, W2",
        "minute": "S1, W1",
        "mirror": "S3, W3",
        "misery": "S3",
        "miss": "S1, W2",
        "mission": "S3, W2",
        "mistake": "S2, W2",
        "mix": "S2, W3",
        "mixed": "S2",
        "mixture": "S3, W3",
        "mobile": "S2",
        "mode": "W3",
        "model": "S2, W1",
        "modern": "S1, W1",
        "mom": "S1",
        "moment": "S1, W1",
        "mommy": "S3",
        "money": "S1, W1",
        "monitor": "S3, W3",
        "month": "S1, W1",
        "mood": "S3, W3",
        "moon": "W3",
        "moral": "S3, W2",
        "more": "S1, W1",
        "moreover": "W2",
        "morning": "S1, W1",
        "mortgage": "W3",
        "most": "S1, W1",
        "mostly": "S2, W3",
        "mother": "S1, W1",
        "motion": "W3",
        "motor": "S3, W3",
        "motorway": "S2",
        "mountain": "S3, W3",
        "mouse": "S2, W3",
        "mouth": "S2, W1",
        "move": "S1, W1",
        "movement": "S1, W1",
        "movie": "S1, W2",
        "much": "S1, W1",
        "mud": "S3",
        "mum": "S1, W2",
        "mummy": "S1",
        "murder": "S3, W2",
        "muscle": "S2, W3",
        "museum": "S3, W2",
        "mushroom": "S3",
        "music": "S1, W1",
        "musical": "S3, W3",
        "must": "S1, W1",
        "my": "S1, W1",
        "myself": "S1, W1",
        "mystery": "W3",
        "nail": "S3",
        "naked": "S3",
        "name": "S1, W1",
        "narrow": "S3, W2",
        "nasty": "S2",
        "nation": "S3, W2",
        "national": "S1, W1",
        "native": "S3, W3",
        "natural": "S2, W1",
        "naturally": "S3, W3",
        "nature": "S1, W1",
        "naughty": "S3",
        "near": "S1, W1",
        "nearby": "W3",
        "nearly": "S1, W1",
        "neat": "S2",
        "necessarily": "S2, W2",
        "necessary": "S2, W1",
        "neck": "S2, W2",
        "need": "S1, W1",
        "negative": "S2, W2",
        "negotiate": "S3, W3",
        "negotiation": "S3, W2",
        "neighbour": "S2, W2",
        "neighbourhood": "S3, W3",
        "neither": "S2, W3",
        "nerve": "S3, W3",
        "nervous": "S3, W3",
        "net": "W3",
        "network": "S3, W2",
        "never": "S1, W1",
        "nevertheless": "S3, W2",
        "new": "S1, W1",
        "newly": "W3",
        "news": "S1, W1",
        "newspaper": "S2, W2",
        "next": "S1, W1",
        "nice": "S1, W2",
        "nicely": "S3",
        "night": "S1, W1",
        "nil": "S3",
        "no": "S1, W1",
        "no way": "S2",
        "nobody": "S1, W2",
        "nod": "W2",
        "noise": "S2, W2",
        "noisy": "S3",
        "none": "S1, W2",
        "nonsense": "S3",
        "nope": "S3",
        "nor": "S2, W1",
        "normal": "S1, W1",
        "normally": "S1, W2",
        "north": "S1, W2",
        "northern": "S2, W2",
        "nose": "S2, W2",
        "not": "S1, W1",
        "notably": "W3",
        "note": "S1, W1",
        "nothing": "S1, W1",
        "notice": "S1, W2",
        "notion": "W3",
        "novel": "W3",
        "now": "S1, W1",
        "nowadays": "S2",
        "nowhere": "S2",
        "nuclear": "W2",
        "nuisance": "S3",
        "number": "S1, W1",
        "numerous": "W3",
        "nurse": "S2, W3",
        "nut": "S3",
        "object": "S3, W2",
        "objection": "S3",
        "objective": "S3, W3",
        "obligation": "W3",
        "observation": "W3",
        "observe": "W2",
        "obtain": "S3, W2",
        "obvious": "S2, W2",
        "obviously": "S1, W2",
        "occasion": "S1, W2",
        "occasional": "S3, W3",
        "occasionally": "S2, W3",
        "occupation": "S3, W3",
        "occupy": "W2",
        "occur": "S1, W1",
        "ocean": "S3, W2",
        "o’clock": "S1, W3",
        "odd": "S1, W3",
        "odds": "S3",
        "of": "S1, W1",
        "off": "S1, W1",
        "offence": "S3, W2",
        "offer": "S1, W1",
        "office": "S1, W1",
        "officer": "S1, W1",
        "official": "S3, W1",
        "often": "S1, W1",
        "oil": "S2, W1",
        "OK": "S1",
        "old": "S1, W1",
        "on": "S1, W1",
        "once": "S1, W1",
        "one number": "S1, W1",
        "one another": "S3, W3",
        "onion": "S3",
        "only": "S1, W1",
        "onto": "S1, W2",
        "open": "S1, W1",
        "opening": "S3",
        "operate": "S2, W2",
        "operation": "S1, W1",
        "operator": "W3",
        "opinion": "S1, W2",
        "opponent": "W3",
        "opportunity": "S1, W1",
        "oppose": "S3, W3",
        "opposite": "S2, W2",
        "opposition": "S3, W2",
        "option": "S1, W2",
        "or": "S1, W1",
        "orange": "S3",
        "order": "S1, W1",
        "ordinary": "S1, W2",
        "organ": "W3",
        "organic": "W3",
        "organization": "S2, W1",
        "organize": "S1, W2",
        "organized": "S3",
        "origin": "W2",
        "original": "S1, W1",
        "originally": "S2, W2",
        "other": "S1, W1",
        "otherwise": "S1, W2",
        "ought to": "S1, W1",
        "ounce": "S3",
        "our": "S1, W1",
        "ours": "S1",
        "ourselves": "S1, W3",
        "out": "S1, W1",
        "outcome": "W3",
        "output": "W2",
        "outside": "S1, W1",
        "outstanding": "W3",
        "oven": "S3",
        "over": "S1, W1",
        "overall": "S3, W2",
        "overcome": "W3",
        "overseas": "W3",
        "overtime": "S3",
        "owe": "S2, W3",
        "own": "S1, W1",
        "owner": "S2, W2",
        "ownership": "W3",
        "pace": "W3",
        "pack": "S2, W3",
        "package": "S2, W2",
        "packet": "S2",
        "pad": "S3",
        "page": "S1, W1",
        "pain": "S2, W2",
        "paint": "S2, W2",
        "painting": "S3, W2",
        "pair": "S2, W2",
        "palace": "W3",
        "pale": "W3",
        "pan": "S3, W3",
        "panel": "S1, W2",
        "panic": "S3",
        "pants": "S3",
        "paper": "S1, W1",
        "parcel": "S3",
        "pardon": "S2",
        "parent": "S1, W1",
        "park": "S1, W2",
        "parking": "S3",
        "parliament": "W2",
        "part": "S1, W1",
        "participate": "W3",
        "particular": "S1, W1",
        "particularly": "S1, W1",
        "partly": "S2, W2",
        "partner": "S2, W2",
        "partnership": "W3",
        "party": "S1, W1",
        "pass": "S1, W1",
        "passage": "W2",
        "passenger": "S3, W2",
        "passion": "W3",
        "past": "S1, W1",
        "path": "S2, W2",
        "patience": "S3",
        "patient": "S2, W1",
        "pattern": "S2, W1",
        "pause": "W3",
        "pay": "S1, W1",
        "payment": "S2, W1",
        "peace": "S2, W2",
        "peaceful": "S3",
        "peak": "W3",
        "pen": "S2",
        "penalty": "W3",
        "pencil": "S2",
        "penny": "S1",
        "pension": "S2, W2",
        "people": "S1, W1",
        "pepper": "S3",
        "per": "S3, W1",
        "perceive": "W3",
        "percent": "S3, W2",
        "percentage": "W3",
        "perception": "W3",
        "perfect": "S2, W2",
        "perfectly": "S2, W3",
        "perform": "S3, W2",
        "performance": "S2, W1",
        "perhaps": "S1, W1",
        "period": "S1, W1",
        "permanent": "S2, W2",
        "permission": "S2, W3",
        "permit": "W3",
        "person": "S1, W1",
        "personal": "S1, W1",
        "personality": "S3, W3",
        "personally": "S2",
        "personnel": "W3",
        "perspective": "W3",
        "persuade": "S3, W2",
        "petrol": "S3",
        "phase": "W2",
        "philosophy": "W3",
        "phone": "S1, W2",
        "photo": "S3, W3",
        "photocopy": "S3, W3",
        "photograph": "S2, W2",
        "phrase": "S3, W3",
        "physical": "S2, W1",
        "physically": "S3",
        "physics": "S3",
        "piano": "S3",
        "pick": "S1, W1",
        "picture": "S1, W1",
        "pie": "S2",
        "piece": "S1, W1",
        "pig": "S2",
        "pile": "S2",
        "pill": "S3",
        "pilot": "W3",
        "pin": "S3",
        "pink": "S2, W3",
        "pint": "S2",
        "pipe": "S2, W3",
        "pitch": "S3, W3",
        "pity": "S3",
        "pizza": "S2",
        "place": "S1, W1",
        "plain": "S2, W3",
        "plan": "S1, W1",
        "plane": "S2, W2",
        "planet": "W3",
        "plant": "S2, W1",
        "plastic": "S2, W2",
        "plate": "S2, W2",
        "platform": "S3, W3",
        "play": "S1, W1",
        "player": "S2, W1",
        "pleasant": "S3, W3",
        "please": "S1, W2",
        "pleased": "S2, W3",
        "pleasure": "S2, W2",
        "plenty": "S1, W1",
        "plot": "W3",
        "plug": "S3",
        "plus": "S1, W2",
        "pocket": "S2, W2",
        "poem": "S3, W3",
        "poet": "W3",
        "poetry": "W3",
        "point": "S1, W1",
        "pole": "W3",
        "police": "S1, W1",
        "policeman": "S2, W3",
        "policy": "S3, W1",
        "polite": "S3",
        "political": "S2, W1",
        "politician": "W2",
        "politics": "S2, W2",
        "poll": "W3",
        "pollution": "W2",
        "pond": "S3",
        "pool": "S2, W2",
        "poor": "S1, W1",
        "pop": "S3, W3",
        "popular": "S2, W1",
        "population": "S2, W1",
        "port": "W2",
        "pose": "W3",
        "position": "S1, W1",
        "positive": "S2, W2",
        "possess": "W3",
        "possession": "W3",
        "possibility": "S2, W2",
        "possible": "S1, W1",
        "possibly": "S1, W2",
        "post": "S2, W2",
        "post office": "S3",
        "poster": "S3",
        "pot": "S2, W3",
        "potato": "S2",
        "potential": "S3, W2",
        "pound": "S1, W2",
        "pour": "S2, W3",
        "poverty": "W3",
        "power": "S1, W1",
        "powerful": "S3, W2",
        "practical": "S3, W2",
        "practically": "S3",
        "practice": "S2, W1",
        "practise": "S3, W3",
        "praise": "W3",
        "pray": "S3, W3",
        "prayer": "S3, W3",
        "precise": "W3",
        "precisely": "S2, W3",
        "predict": "W3",
        "prefer": "S2, W2",
        "preference": "W3",
        "pregnant": "S3",
        "premise": "W3",
        "preparation": "S3, W3",
        "prepare": "S1, W1",
        "prepared": "S2",
        "presence": "S3, W2",
        "present": "S2, W1",
        "presentation": "S2, W3",
        "preserve": "W3",
        "president": "S2, W2",
        "press": "S2, W2",
        "pressure": "S1, W1",
        "presumably": "S1, W3",
        "presume": "S3",
        "pretend": "S2, W3",
        "pretty": "S2, W3",
        "prevent": "S2, W1",
        "previous": "S1, W1",
        "previously": "S3, W2",
        "price": "S1, W1",
        "pride": "S3, W3",
        "priest": "W3",
        "primarily": "W3",
        "primary": "S2, W2",
        "prince": "W3",
        "princess": "W3",
        "principal": "W2",
        "principle": "S2, W1",
        "print": "S2, W3",
        "printer": "S3, W3",
        "prior": "W3",
        "priority": "S2, W2",
        "prison": "S2, W2",
        "prisoner": "S3, W2",
        "private": "S1, W1",
        "privilege": "W3",
        "prize": "S2, W2",
        "probably": "S1, W1",
        "problem": "S1, W1",
        "procedure": "S2, W2",
        "proceed": "S3, W3",
        "proceeding": "W2",
        "process": "S1, W1",
        "produce": "S1, W1",
        "producer": "W3",
        "product": "S1, W1",
        "production": "S1, W1",
        "profession": "W3",
        "professional": "S2, W1",
        "professor": "S3, W3",
        "profile": "W3",
        "profit": "S1, W1",
        "program": "W1",
        "programme": "S1, W1",
        "progress": "S2, W2",
        "project": "S1, W1",
        "promise": "S2, W2",
        "promote": "S3, W2",
        "promotion": "S3, W3",
        "prompt": "W3",
        "proof": "S3, W3",
        "proper": "S1, W2",
        "properly": "S1, W2",
        "property": "S2, W1",
        "proportion": "S2, W2",
        "proposal": "S2, W1",
        "propose": "S2, W2",
        "proposed": "W3",
        "prosecution": "W3",
        "prospect": "W2",
        "protect": "S2, W2",
        "protection": "S2, W2",
        "protest": "W3",
        "proud": "S2, W3",
        "prove": "S2, W1",
        "provide": "S1, W1",
        "provided": "S3, W2",
        "providing": "S2",
        "provision": "S3, W1",
        "psychological": "W3",
        "psychology": "W3",
        "pub": "S2, W3",
        "public": "S1, W1",
        "publication": "W2",
        "publicity": "S3, W3",
        "publish": "S3, W1",
        "publisher": "W3",
        "pudding": "S3",
        "pull": "S1, W1",
        "punch": "S3",
        "punishment": "W3",
        "pupil": "S2, W1",
        "purchase": "W3",
        "pure": "S3, W3",
        "purely": "S3, W3",
        "purple": "S3",
        "purpose": "S2, W2",
        "purse": "S3",
        "pursue": "S3, W2",
        "push": "S1, W2",
        "put": "S1, W1",
        "qualification": "W3",
        "qualify": "S3, W3",
        "quality": "S1, W1",
        "quantity": "S3, W2",
        "quarter": "S1, W2",
        "queen": "S2, W2",
        "question": "S1, W1",
        "queue": "S3",
        "quick": "S1, W2",
        "quickly": "S1, W1",
        "quid": "S2",
        "quiet": "S2, W2",
        "quietly": "S3, W3",
        "quit": "S3",
        "quite": "S1, W1",
        "quote": "S2, W3",
        "race": "S2, W2",
        "racing": "S3",
        "radical": "W3",
        "radio": "S1, W2",
        "rail": "S2, W2",
        "railway": "S2, W2",
        "rain": "S2, W2",
        "raise": "S1, W1",
        "range": "S1, W1",
        "rank": "W3",
        "rapid": "W3",
        "rapidly": "W3",
        "rare": "S3, W2",
        "rarely": "W2",
        "rate": "S1, W1",
        "rather": "S1, W1",
        "ratio": "W3",
        "raw": "W3",
        "reach": "S1, W1",
        "react": "S3, W3",
        "reaction": "S2, W2",
        "read": "S1, W1",
        "reader": "S3, W2",
        "readily": "W3",
        "reading": "W2",
        "ready": "S1, W2",
        "real": "S1, W1",
        "realistic": "S3",
        "reality": "S2, W2",
        "realize": "S1, W1",
        "really": "S1, W1",
        "reason": "S1, W1",
        "reasonable": "S1, W2",
        "reasonably": "S2, W3",
        "recall": "S3, W2",
        "receipt": "S2",
        "receive": "S1, W1",
        "recent": "S2, W1",
        "recently": "S1, W1",
        "reception": "W3",
        "recipe": "S3",
        "reckon": "S1, W3",
        "recognition": "S3, W2",
        "recognize": "S1, W1",
        "recommend": "S2, W2",
        "recommendation": "S3, W3",
        "record": "S1, W1",
        "recording": "W3",
        "recover": "W2",
        "recovery": "W3",
        "red": "S1, W1",
        "reduce": "S1, W1",
        "reduction": "S3, W2",
        "refer": "S1, W1",
        "reference": "S2, W1",
        "reflect": "S2, W1",
        "reflection": "W3",
        "reform": "W2",
        "refrigerator": "S3",
        "refuse": "S2, W1",
        "regard": "S3",
        "regime": "W2",
        "region": "S1, W1",
        "regional": "S1, W2",
        "register": "S3, W3",
        "registration": "S3",
        "regret": "W3",
        "regular": "S2, W2",
        "regularly": "S3, W3",
        "regulation": "S2, W2",
        "reinforce": "W3",
        "reject": "S3, W2",
        "relate": "S2, W1",
        "related": "S2, W3",
        "relation": "S2, W1",
        "relationship": "S1, W1",
        "relative": "W2",
        "relatively": "S2, W2",
        "relax": "S3, W3",
        "release": "S2, W2",
        "relevant": "S2, W2",
        "relief": "S2, W2",
        "relieve": "S3",
        "religion": "S2, W2",
        "religious": "S2, W2",
        "rely": "S3, W2",
        "remain": "S1, W1",
        "remaining": "W2",
        "remains": "W3",
        "remark": "W3",
        "remarkable": "W3",
        "remember": "S1, W1",
        "remind": "S1, W2",
        "remote": "W3",
        "remove": "S2, W1",
        "rent": "S2, W3",
        "repair": "W3",
        "repeat": "S2, W2",
        "replace": "S2, W1",
        "replacement": "W3",
        "reply": "S3, W3",
        "report": "S2, W1",
        "reporter": "S3",
        "represent": "S2, W1",
        "representation": "S3, W2",
        "representative": "S3, W2",
        "republic": "W2",
        "reputation": "W3",
        "request": "S3, W2",
        "require": "S1, W1",
        "requirement": "S2, W2",
        "rescue": "S3, W3",
        "research": "S2, W1",
        "reserve": "S3",
        "resident": "S3, W3",
        "residential": "W3",
        "resign": "W3",
        "resignation": "W3",
        "resist": "W3",
        "resistance": "S3, W3",
        "resolution": "W3",
        "resolve": "W3",
        "resort": "W3",
        "resource": "S2, W1",
        "respect": "S1, W1",
        "respectively": "W3",
        "respond": "S2, W2",
        "response": "S1, W1",
        "responsibility": "S2, W1",
        "responsible": "S2, W2",
        "rest": "S1, W1",
        "restaurant": "S2, W2",
        "restore": "W3",
        "restrict": "W3",
        "restriction": "W3",
        "result": "S1, W1",
        "retain": "W2",
        "retire": "S2, W3",
        "retirement": "S3, W3",
        "return": "S2, W1",
        "reveal": "W1",
        "revenue": "W2",
        "reverse": "W3",
        "review": "S2, W2",
        "revolution": "S3, W2",
        "reward": "W3",
        "rhythm": "W3",
        "rice": "S3",
        "rich": "S2, W2",
        "rid": "S1",
        "ride": "S2, W2",
        "ridiculous": "S2",
        "right": "S1, W1",
        "ring": "S1, W2",
        "rip": "S3",
        "rise": "S2, W1",
        "risk": "S2, W1",
        "rival": "W3",
        "river": "S2, W2",
        "road": "S1, W1",
        "rob": "S3",
        "rock": "S2, W2",
        "role": "S2, W1",
        "roll": "S1, W2",
        "roof": "S2, W2",
        "room": "S1, W1",
        "root": "S2, W2",
        "rope": "S3, W3",
        "rough": "S2, W3",
        "roughly": "S2",
        "round": "S1, W2",
        "route": "S3, W2",
        "routine": "W3",
        "row": "S2, W2",
        "royal": "S3, W1",
        "rub": "S2",
        "rubber": "S3",
        "rubbish": "S2",
        "rude": "S3",
        "ruin": "S3",
        "rule": "S1, W1",
        "run": "S1, W1",
        "rural": "W2",
        "rush": "S2, W3",
        "sack": "S3",
        "sad": "S2, W3",
        "safe": "S2, W2",
        "safety": "S2, W2",
        "sail": "S3",
        "sake": "S2, W3",
        "salad": "S2",
        "salary": "S2, W3",
        "sale": "S1, W1",
        "salt": "S2, W3",
        "same": "S1, W1",
        "sample": "S3, W2",
        "sand": "S3, W3",
        "sandwich": "S2",
        "satellite": "W3",
        "satisfaction": "W3",
        "satisfied": "S3",
        "satisfy": "S3, W2",
        "sauce": "S3",
        "sausage": "S3",
        "save": "S1, W1",
        "saving": "S3, W3",
        "say": "S1, W1",
        "scale": "S2, W2",
        "scared": "S3",
        "scene": "S2, W2",
        "schedule": "S2, W3",
        "scheme": "S2, W1",
        "school": "S1, W1",
        "science": "S1, W1",
        "scientific": "S3, W2",
        "scientist": "S3, W2",
        "scope": "W3",
        "score": "S2, W2",
        "scratch": "S3",
        "scream": "S3",
        "screen": "S2, W2",
        "screw": "S3",
        "script": "S3",
        "sea": "S2, W1",
        "seal": "S3",
        "search": "S3, W2",
        "season": "S2, W1",
        "seat": "S2, W1",
        "second number": "S1, W1",
        "secondary": "S3, W2",
        "secondly": "S3",
        "secret": "S3, W2",
        "secretary": "S2, W1",
        "section": "S1, W1",
        "sector": "W1",
        "secure": "S3, W3",
        "security": "W1",
        "see": "S1, W1",
        "seed": "S3, W3",
        "seek": "S2, W1",
        "seem": "S1, W1",
        "seize": "W3",
        "select": "S2, W2",
        "selection": "S3, W2",
        "self": "S2, W3",
        "sell": "S1, W1",
        "send": "S1, W1",
        "senior": "W2",
        "sense": "S1, W1",
        "sensible": "S3, W3",
        "sensitive": "S3, W3",
        "sentence": "S1, W2",
        "separate": "S2, W2",
        "sequence": "W2",
        "series": "S2, W1",
        "serious": "S1, W1",
        "seriously": "S2, W2",
        "servant": "W2",
        "serve": "S1, W1",
        "service": "S1, W1",
        "session": "S2, W2",
        "set": "S1, W1",
        "setting": "W2",
        "settle": "S2, W2",
        "settlement": "W2",
        "several": "S1, W1",
        "severe": "S3, W3",
        "sew": "S3",
        "sex": "S1, W2",
        "sexual": "S3, W2",
        "shadow": "S3, W2",
        "shake": "S3, W2",
        "shall": "S1, W1",
        "shame": "S2",
        "shape": "S2, W2",
        "share": "S1, W1",
        "sharp": "S3, W2",
        "sharply": "W3",
        "shave": "S3",
        "she": "S1, W1",
        "shed": "S3",
        "sheep": "S2, W3",
        "sheet": "S1, W2",
        "shelf": "S3, W3",
        "shell": "S3, W3",
        "shelter": "W3",
        "shift": "S3, W3",
        "shine": "S3",
        "ship": "S2, W2",
        "shirt": "S2, W3",
        "shock": "S2, W2",
        "shocked": "S3",
        "shocking": "S3",
        "shoe": "S1, W3",
        "shoot": "S2, W2",
        "shop": "S1, W1",
        "shopping": "S2, W3",
        "short": "S1, W1",
        "shortly": "S3, W3",
        "shot": "S2, W2",
        "should": "S1, W1",
        "shoulder": "S2, W2",
        "shout": "S2, W2",
        "shove": "S3",
        "show": "S1, W1",
        "shower": "S2",
        "shrug": "W3",
        "shut": "S1, W2",
        "sick": "S1, W3",
        "side": "S1, W1",
        "sight": "S2, W2",
        "sign": "S3, W2",
        "signal": "S2, W2",
        "signature": "S3",
        "significance": "W2",
        "significant": "S2, W1",
        "significantly": "S3, W2",
        "silence": "W2",
        "silent": "W3",
        "silly": "S2",
        "silver": "S3",
        "similar": "S1, W1",
        "similarly": "W3",
        "simple": "S1, W1",
        "simply": "S1, W1",
        "sin": "S2",
        "since": "S1, W1",
        "sing": "S1, W2",
        "singer": "S3",
        "single": "S1, W1",
        "sink": "S3",
        "sir": "S1, W3",
        "sister": "S1, W1",
        "sit": "S1, W1",
        "site": "S1, W2",
        "situation": "S1, W1",
        "size": "S1, W1",
        "skill": "S2, W1",
        "skin": "S2, W2",
        "skirt": "S3",
        "sky": "S2, W2",
        "sleep": "S1, W2",
        "slice": "S3",
        "slide": "S3, W3",
        "slight": "S2, W3",
        "slightly": "S1, W2",
        "slim": "S3",
        "slip": "S3, W2",
        "slope": "W3",
        "slow": "S2, W2",
        "slowly": "S3, W2",
        "small": "S1, W1",
        "smart": "S2, W2",
        "smell": "S2, W3",
        "smile": "S2, W2",
        "smoke": "S3, W3",
        "smoking": "S2",
        "smooth": "W3",
        "snap": "W3",
        "snow": "S2, W3",
        "so": "S1, W1",
        "soap": "S3",
        "so-called": "W3",
        "social": "S1, W1",
        "society": "S1, W1",
        "sock": "S3",
        "soft": "S2, W2",
        "software": "S3, W2",
        "soil": "W2",
        "soldier": "S3, W2",
        "sole": "W3",
        "solicitor": "S3, W2",
        "solid": "S3, W3",
        "solution": "S2, W1",
        "solve": "S2, W3",
        "some": "S1, W1",
        "somebody": "S1, W3",
        "somehow": "S2, W2",
        "someone": "S1, W1",
        "something": "S1, W1",
        "sometimes": "S1, W1",
        "somewhat": "S3, W2",
        "somewhere": "S1, W2",
        "son": "S1, W1",
        "song": "S1, W2",
        "soon": "S1, W1",
        "sore": "S3",
        "sorry": "S1, W2",
        "sort": "S1, W1",
        "soul": "S3, W3",
        "sound": "S1, W1",
        "soup": "S3",
        "source": "S2, W1",
        "south": "S1, W2",
        "southern": "S2, W2",
        "space": "S1, W1",
        "spare": "S2",
        "speak": "S1, W1",
        "speaker": "S2, W2",
        "special": "S1, W1",
        "specialist": "S3, W3",
        "species": "W2",
        "specific": "S1, W1",
        "specifically": "S2, W3",
        "specify": "W3",
        "speech": "S2, W2",
        "speed": "S2, W1",
        "spell": "S2",
        "spelling": "S2",
        "spend": "S1, W1",
        "spill": "S3",
        "spin": "S3",
        "spirit": "S2, W2",
        "spiritual": "W3",
        "spite": "W3",
        "split": "S2, W3",
        "spoil": "S3",
        "spokesman": "W2",
        "spoon": "S3",
        "sport": "S2, W2",
        "spot": "S2, W2",
        "spray": "S3",
        "spread": "S2, W2",
        "spring": "S2, W2",
        "squad": "W3",
        "square": "S2, W3",
        "squeeze": "S3",
        "stable": "W3",
        "staff": "S2, W2",
        "stage": "S1, W1",
        "stair": "S2, W3",
        "stake": "W3",
        "stall": "S3",
        "stamp": "S1, W1",
        "stand": "S1, W1",
        "standard": "S2, W2",
        "star": "S2, W2",
        "stare": "S3, W2",
        "start": "S1, W1",
        "starve": "S3",
        "state": "S1, W2",
        "statement": "S2, W1",
        "station": "S1, W1",
        "statistic": "S2, W3",
        "status": "W2",
        "stay": "S3",
        "steady": "W3",
        "steak": "S3",
        "steal": "S3, W3",
        "steam": "W3",
        "steel": "S3, W3",
        "steep": "S3",
        "step": "S2, W1",
        "stick": "S1, W3",
        "stiff": "S3",
        "still": "S1, W1",
        "stir": "S3, W3",
        "stock": "S2, W2",
        "stomach": "S3, W3",
        "stone": "S2, W1",
        "stop": "S1, W1",
        "storage": "W3",
        "store": "S1, W1",
        "storm": "W3",
        "story": "S1, W1",
        "straight": "S1, W2",
        "straightforward": "S3",
        "strain": "W3",
        "strange": "S2, W2",
        "stranger": "S2, W2",
        "strategic": "W3",
        "strategy": "W2",
        "straw": "S3",
        "strawberry": "S3",
        "stream": "W3",
        "street": "S1, W1",
        "strength": "S2, W2",
        "strengthen": "W3",
        "stress": "S3, W3",
        "stretch": "S3, W3",
        "strict": "S3",
        "strike": "S3, W2",
        "string": "S3, W2",
        "strip": "W3",
        "stroke": "S3",
        "strong": "S1, W1",
        "strongly": "S3",
        "structure": "S3, W2",
        "struggle": "S3, W3",
        "student": "S1, W1",
        "studio": "S3, W2",
        "study": "S2, W3",
        "stuff": "S1, W3",
        "stupid": "S1, W3",
        "style": "S2, W1",
        "subject": "S2, W1",
        "submit": "S3, W3",
        "subsequent": "W2",
        "subsequently": "W3",
        "substance": "W3",
        "substantial": "S3, W2",
        "succeed": "S3, W2",
        "success": "S1, W1",
        "successful": "S2, W1",
        "successfully": "W3",
        "such": "S1, W1",
        "suck": "S3",
        "sudden": "S2, W3",
        "suddenly": "S1, W1",
        "suffer": "S1, W1",
        "sufficient": "S2, W2",
        "sugar": "S2, W3",
        "suggest": "S1, W1",
        "suggestion": "S1, W2",
        "suit": "S2, W3",
        "suitable": "S3, W2",
        "sum": "S2, W2",
        "summer": "S1, W1",
        "sun": "S2, W1",
        "super": "S2",
        "supermarket": "S3",
        "supper": "S3",
        "supply": "S2, W2",
        "support": "S1, W1",
        "supporter": "S3, W2",
        "suppose": "S1, W1",
        "sure": "S1, W1",
        "surely": "S1, W2",
        "surface": "S3, W1",
        "surgery": "S2, W2",
        "surprise": "S3, W2",
        "surprised": "S2, W2",
        "surprising": "S3, W3",
        "surprisingly": "W3",
        "surround": "W2",
        "survey": "S2, W2",
        "survival": "W3",
        "survive": "S2, W2",
        "suspect": "S2, W3",
        "suspicion": "W3",
        "suspicious": "S3",
        "sustain": "W3",
        "swap": "S3",
        "swear": "S2",
        "sweep": "W3",
        "sweet": "S2, W3",
        "swim": "S3",
        "swimming": "S2",
        "swing": "W3",
        "switch": "S2, W3",
        "symbol": "W3",
        "sympathy": "W3",
        "system": "S1, W1",
        "table": "S1, W1",
        "tablet": "S3",
        "tackle": "S3, W3",
        "tail": "S2, W3",
        "take": "S1, W1",
        "tale": "W3",
        "talent": "W3",
        "talk": "S1, W1",
        "tall": "S2, W2",
        "tank": "S2, W2",
        "tap": "S3",
        "tape": "S3, W3",
        "target": "S2, W2",
        "task": "S2, W1",
        "taste": "S2, W2",
        "tax": "S1, W1",
        "taxi": "S3",
        "tea": "S1, W2",
        "teach": "S1, W2",
        "teacher": "S1, W1",
        "teaching": "S2, W2",
        "team": "S1, W1",
        "tear": "S3, W3",
        "technical": "S2, W2",
        "technique": "S3, W1",
        "technology": "S2, W1",
        "telephone": "S1, W2",
        "television": "S1, W1",
        "tell": "S1, W1",
        "telly": "S2",
        "temperature": "S2, W2",
        "temporary": "S3, W3",
        "tend": "S1, W1",
        "tendency": "S3, W3",
        "tennis": "S3, W3",
        "tension": "W2",
        "tent": "S3",
        "term": "S1, W1",
        "terrible": "S1, W3",
        "terribly": "S2",
        "territory": "W2",
        "terror": "W3",
        "terrorist": "W3",
        "test": "S1, W1",
        "text": "S2, W1",
        "than": "S1, W1",
        "thank": "S1, W2",
        "thanks": "S1",
        "that": "S1, W2",
        "determiner": "S1, W1",
        "theatre": "S2, W2",
        "their": "S1, W1",
        "theirs": "S3",
        "them": "S1, W1",
        "theme": "S2, W2",
        "themselves": "S1, W1",
        "then": "S1, W1",
        "theoretical": "W3",
        "theory": "S2, W1",
        "there": "S1, W1",
        "therefore": "S1, W1",
        "they": "S1, W1",
        "thick": "S2, W2",
        "thin": "S2, W2",
        "thing": "S1, W1",
        "think": "S1, W1",
        "this": "S1, W1",
        "though": "S1",
        "thought": "S1, W1",
        "threat": "S3, W2",
        "threaten": "S3, W2",
        "three number": "S1",
        "throat": "S3, W3",
        "through": "S1, W1",
        "throughout": "S2, W1",
        "throw": "S1, W1",
        "thus": "W1",
        "ticket": "S1, W2",
        "tidy": "S3",
        "tie": "S2, W3",
        "tight": "S2, W3",
        "tile": "S3",
        "till": "S1",
        "time": "S1, W1",
        "tin": "S2",
        "tiny": "S2, W2",
        "tip": "S2, W3",
        "tired": "S1, W2",
        "title": "S3, W1",
        "to": "S1, W1",
        "toast": "S3",
        "today": "S1, W1",
        "toe": "S3",
        "together": "S1, W1",
        "toilet": "S2",
        "tomato": "S2",
        "tomorrow": "S1, W2",
        "ton": "S3",
        "tone": "S3, W2",
        "tongue": "S3, W3",
        "tonight": "S1, W2",
        "too": "S1, W1",
        "tool": "S2, W2",
        "tooth": "S2, W2",
        "top": "S1, W1",
        "topic": "S3, W2",
        "total": "S1, W1",
        "totally": "S1, W2",
        "touch": "S2, W2",
        "tough": "S2, W2",
        "tour": "S3, W2",
        "tourist": "W3",
        "towards": "S1, W1",
        "towel": "S3",
        "tower": "S3, W3",
        "town": "S1, W1",
        "toy": "S3",
        "track": "S2, W2",
        "trade": "S3, W1",
        "tradition": "S2, W2",
        "traditional": "S3, W1",
        "traffic": "S1, W2",
        "trailer": "S3",
        "train": "S1, W2",
        "trainer": "S3",
        "training": "S2, W1",
        "transaction": "S3, W3",
        "transfer": "S3, W2",
        "transform": "W3",
        "transition": "W3",
        "translate": "S3",
        "transport": "S2, W2",
        "transportation": "W3",
        "trash": "S3",
        "travel": "S2, W2",
        "tray": "S3",
        "treat": "S3",
        "treatment": "S2, W1",
        "treaty": "W2",
        "tree": "S1, W1",
        "tremendous": "S2",
        "trend": "S3, W2",
        "trial": "S3, W2",
        "trick": "S3",
        "tricky": "S3",
        "trip": "S2, W2",
        "troop": "W2",
        "trouble": "S1, W2",
        "trousers": "S2",
        "truck": "S2, W3",
        "true": "S1, W1",
        "truly": "W3",
        "trust": "S1, W2",
        "truth": "S1, W2",
        "try": "S3",
        "tube": "S3, W3",
        "tune": "S3",
        "tunnel": "W3",
        "turn": "S1, W1",
        "TV": "S2, W2",
        "twice": "S2, W2",
        "twist": "S3",
        "type": "S1, W1",
        "typical": "S2, W2",
        "tyre": "S3",
        "ugly": "S3",
        "ultimate": "W3",
        "ultimately": "W3",
        "unable": "W2",
        "unbelievable": "S3",
        "uncle": "S2, W3",
        "under": "S1, W1",
        "underneath": "S2",
        "understand": "S1, W1",
        "understanding": "W3",
        "undertake": "W3",
        "unemployed": "S2, W3",
        "unemployment": "S2, W2",
        "unfair": "S3",
        "unfortunate": "S3",
        "unfortunately": "S1, W3",
        "unhappy": "S3",
        "uniform": "S3",
        "union": "S1, W1",
        "unique": "S3, W2",
        "unit": "S2, W2",
        "united": "S2, W3",
        "unity": "W3",
        "universal": "W3",
        "universe": "W3",
        "university": "S2, W1",
        "unknown": "W2",
        "unless": "S1, W1",
        "unlike": "W3",
        "unlikely": "S3, W2",
        "until": "S1, W1",
        "unusual": "S2, W3",
        "up": "S1, W1",
        "upon": "S2, W1",
        "upper": "W2",
        "upset": "S2",
        "upstairs": "S2",
        "urban": "W2",
        "urge": "W3",
        "urgent": "S3",
        "us": "S1, W1",
        "use": "S1, W1",
        "used": "S1, W2",
        "useful": "S1, W1",
        "user": "S3, W1",
        "usual": "S2, W2",
        "usually": "S1, W1",
        "vacation": "S2, W3",
        "vague": "S3",
        "valley": "S3, W3",
        "valuable": "W3",
        "value": "S2, W1",
        "van": "S2, W3",
        "variation": "W2",
        "variety": "S2, W1",
        "various": "S1, W1",
        "vary": "S3, W2",
        "vast": "S3, W2",
        "vegetable": "S3, W3",
        "vehicle": "S2, W2",
        "version": "S2, W2",
        "very": "S1, W1",
        "vet": "S3",
        "via": "W2",
        "victim": "S3, W2",
        "victory": "W2",
        "video": "S1, W2",
        "view": "S1, W1",
        "village": "S1, W1",
        "violence": "S2, W2",
        "violent": "S3, W3",
        "virtually": "S2, W2",
        "virtue": "W3",
        "virus": "W3",
        "visible": "W3",
        "vision": "S3, W2",
        "visit": "S2, W1",
        "visitor": "S3, W2",
        "visual": "W3",
        "vital": "W2",
        "voice": "S2, W1",
        "volume": "S3, W2",
        "voluntary": "W3",
        "vote": "S2, W2",
        "vulnerable": "W3",
        "wage": "S2, W2",
        "wait": "S1, W1",
        "wake": "S2, W3",
        "walk": "S1, W1",
        "wall": "S1, W1",
        "wander": "S3",
        "want": "S1, W1",
        "war": "S2, W1",
        "ward": "W3",
        "wardrobe": "S3",
        "warm": "S2, W2",
        "warn": "S3, W2",
        "warning": "S3, W2",
        "wash": "S1, W3",
        "washing": "S2",
        "waste": "S2, W3",
        "watch": "S1, W1",
        "water": "S1, W1",
        "wave": "S3, W2",
        "way": "S1, W1",
        "we": "S1, W1",
        "weak": "S3, W2",
        "weakness": "W3",
        "wealth": "W3",
        "weapon": "S3, W2",
        "wear": "S1, W1",
        "weather": "S1, W2",
        "web": "S2, W2",
        "website": "S2, W2",
        "wedding": "S2, W3",
        "week": "S1, W1",
        "weekend": "S1, W2",
        "weekly": "W3",
        "weigh": "S3, W3",
        "weight": "S1, W2",
        "weird": "S2",
        "welcome": "S2, W3",
        "welfare": "S3, W2",
        "well": "S1, W1",
        "west": "S1, W2",
        "western": "S2, W2",
        "wet": "S2, W3",
        "what": "S1, W1",
        "whatever": "S1, W1",
        "whatsoever": "S2",
        "wheel": "S2, W3",
        "when": "S1, W1",
        "whenever": "S2, W3",
        "where": "S1, W1",
        "whereas": "S2, W2",
        "wherever": "S2",
        "whether": "S1, W1",
        "which": "S1, W1",
        "while": "S1, W1",
        "whisky": "S3",
        "whisper": "W3",
        "white": "S1, W1",
        "who": "S1, W1",
        "whoever": "S2",
        "whole": "S1, W1",
        "whom": "S3, W1",
        "whose": "S2, W1",
        "why": "S1, W1",
        "wicked": "S3",
        "wide": "S1, W1",
        "widely": "W2",
        "widespread": "W3",
        "wife": "S1, W1",
        "wild": "S2, W2",
        "will": "S1, W1",
        "willing": "S2, W3",
        "win": "S1, W1",
        "wind": "S2, W2",
        "window": "S1, W1",
        "windy": "S3",
        "wine": "S2, W2",
        "wing": "S2, W2",
        "winner": "S3, W2",
        "winter": "S2, W2",
        "wipe": "S3",
        "wire": "S2, W3",
        "wise": "S3",
        "wish": "S1, W1",
        "with": "S1, W1",
        "withdraw": "S3, W2",
        "within": "S1, W1",
        "without": "S1, W1",
        "witness": "S2, W3",
        "woman": "S1, W1",
        "wonder": "S1, W2",
        "wonderful": "S1, W2",
        "wood": "S2, W2",
        "wooden": "S3, W3",
        "wool": "S3",
        "word": "S1, W1",
        "work": "S1, W1",
        "worker": "S2, W1",
        "working": "S2, W2",
        "workshop": "S3, W3",
        "world": "S1, W1",
        "worried": "S2, W3",
        "worry": "S1, W2",
        "worrying": "S3",
        "worse": "S2, W2",
        "worth": "S1, W2",
        "would": "S1, W1",
        "wound": "W3",
        "wrap": "S3",
        "write": "S1, W1",
        "writer": "S3, W2",
        "writing": "S2, W3",
        "wrong": "S1, W1",
        "yard": "S2, W2",
        "yeah": "S1",
        "year": "S1, W1",
        "yellow": "S2, W3",
        "yep": "S1",
        "yes": "S1, W1",
        "yesterday": "S1, W1",
        "yet": "S1, W1",
        "you": "S1, W1",
        "young": "S1, W1",
        "youngster": "S3",
        "your": "S1, W1",
        "yours": "S1, W3",
        "yourself": "S1, W2",
        "youth": "S2, W2",
        "zone": "W3"
        }
